name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read # 簡化權限需求
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # 請確認這個 Secret 名稱跟你的 GitHub Settings -> Secrets 裡的一模一樣
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_MUSHROOM_00185380F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # 用於評論 PR
          action: "upload"
          
          ###### 針對 Vue (Vite) 的關鍵設定 ######
          app_location: "/"         # 程式碼在根目錄
          api_location: ""          # 沒有後端 API 程式碼
          output_location: "dist"   # Vite 預設打包輸出的資料夾名稱
          ###### End of Configuration ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_MUSHROOM_00185380F }}
          action: "close"
